### PR TITLE
Created MobileSearch Styled Components

### PR DESCRIPTION
**Pull request by thecodeclimber**

### CODE REVIEW

**Comment by thecodeclimber** [comment]
@lokesh75way 

Please check this error out (and if possible, fix it):

```

05:06:09.487 | Failed to compile.
-- | --
05:06:09.487 | ./src/components/shared/RegisterForm.tsx:107:37
05:06:09.487 | Type error: Parameter 'value' implicitly has an 'any' type.
05:06:09.487 | 105 \|                         required: true,
05:06:09.487 | 106 \|                         validate: {
05:06:09.488 | > 107 \|                             match: (value) => value === getValues(`${ns}password`),
05:06:09.488 | \|                                     ^
05:06:09.488 | 108 \|                         },
05:06:09.488 | 109 \|                     })}
05:06:09.488 | 110 \|                 />
05:06:09.519 | error Command failed with exit code 1.
05:06:09.519 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
05:06:09.535 | Error: Command "yarn run build" exited with 1

```

Thanks.

**Comment by thecodeclimber** [comment]
@lokesh75way 

P.S.  Please let me know how you fixed it :).

**Comment by lokesh75way** [comment]
Hi @thecodeclimber,
This issue seems to be related to the` develop` branch.

**Comment by lokesh75way** [comment]
Hi @thecodeclimber,
This issue is resolved by downgrading the `react-hook-form` version to `6.7.0`.
Please let me know is there any compulsion to upgrade this version?

**Pull request merged**
